package com.zhou.movies.command.impl;

import com.zhou.movies.pojo.Movie;
import com.zhou.movies.service.MovieService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.mockito.Mockito.*;

/**
 * Unit tests for DeleteMovieCommand
 * Goal: verify execute/undo logic with mocked MovieService
 */
@ExtendWith(MockitoExtension.class)
class DeleteMovieCommandTest {

    @Mock
    private MovieService mockService;

    private Movie fakeMovieToDelete; // Memento
    private String randomId;          // store autogenerated ID

    private DeleteMovieCommand deleteMovieCommand;

    @BeforeEach
    void setUp() {
        // Original Memento with random ID
        fakeMovieToDelete = new Movie.Builder("Movie To Delete", "Director")
                .build();
        randomId = fakeMovieToDelete.getId();

        deleteMovieCommand = new DeleteMovieCommand(mockService, fakeMovieToDelete);
    }

    @Test
    @DisplayName("Execute should call service.deleteMovie with Memento ID")
    void execute_WhenCalled_ShouldCallServiceDeleteWithMementoId() throws Exception {
        deleteMovieCommand.execute();

        verify(mockService, times(1)).deleteMovie(randomId); // verify delete called once with correct ID
    }

    @Test
    @DisplayName("Undo should call service.addMovieObject with Memento")
    void undo_WhenCalled_ShouldCallServiceAddWithMemento() throws Exception {
        deleteMovieCommand.undo();

        verify(mockService, times(1)).addMovieObject(fakeMovieToDelete); // verify original restored
    }
}
